project:
  type: website

website:
  title: "Estatistica Descritiva"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: 01-intro.qmd
        text: Introdução à Estatística Descritiva
      - href: 02-analise-explo-dados.qmd
        text: Análise Exploratória de Dados
      - href: 03-medidas-dispersao.qmd
        text: Medidas de Dispersão
      - href: 04-distribuicoes-frequencia.qmd
        text: Distribuições de Frequência 
      - href: 05-graficos-estatisticos.qmd
        text: Gráficos Estatísticos
      - href: 06-exercicios.qmd
        text: Exercícios e Aplicações
      - href: 07-ex-inter.qmd
        text: Exercícios Interactivos
      - href: 08-referencias.qmd
        text: Referências
      